### ISSUE TITLE
Why mark delegate.h as obsolete

### ISSUE THREAD

**Issue by yxbh** [user1095108/generic#1]
Hi, this is not a real issue.

I've been following your library since before you moved it to Github. I was wondering why you moved the delegate class to be obsolete?

Cheers

**Comment by user1095108** [comment]
I use the new forwarder.hpp mostly as most std::function implementations have improved to the point where I thought the old delegate.hpp was obsolete.

**Comment by user1095108** [comment]
Don't forget anyfunction.hpp as well. It's the best thing.

**Comment by user1095108** [comment]
Also check out anyfunction.cpp and the crl library, if you're interested in delegates, signals and slots.

**Comment by yxbh** [comment]
Ok, cool! Thanks . I will definitely check them out! :)

**Comment by user1095108** [comment]
If you want an example for something, just tell me and I'll write one.

**Comment by yxbh** [comment]
I've finally had some time off work to have a look at any_function and wow it is amazing the kind of things you can do with it :o

However, it doesn't look like it supports equality comparison which delegate does.

Also, the current version of delegate.hpp incorrectly fails the equality comparison between two delegate that were constructed from the same inlined function. Adding the following code into operator== fixes the problem. I believe that was actually there a long time ago but it was then removed?
```
if (store_size_ && rhs.store_size_)
    return (std::memcmp(store_.get(), rhs.store_.get(), store_size_) == 0) && (stub_ptr_ == rhs.stub_ptr_);
```

I really want to thank you for making these source code open sourced. I've learnt so much about C++ from your library!

**Comment by user1095108** [comment]
ok, I'll add since it's already obsolete :) Adding memcmp into c++ is a bad idea though. It works on your platform, but how about some other? Delegates are in general very weak when it comes to comparisons.
